# Generated by Django 2.2.4 on 2019-08-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('target_email', models.EmailField(max_length=254, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.IntegerField()),
            ],
        ),
    ]
