# Generated by Django 2.2.4 on 2019-08-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='token',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
