# Generated by Django 2.2.4 on 2019-08-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Univ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=20)),
                ('url_name', models.CharField(max_length=10)),
                ('short_name', models.CharField(max_length=10)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='univ/logo/')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
