# Generated by Django 2.2.4 on 2019-08-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='will_graduate_in',
        ),
    ]
