# Generated by Django 2.2.4 on 2019-08-22 18:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0005_post_viewed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_double_check',
            field=models.ManyToManyField(blank=True, related_name='double_check', to=settings.AUTH_USER_MODEL),
        ),
    ]
