# Generated by Django 2.2.4 on 2019-08-24 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_post_views_double_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_double_check',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='board/post/images/'),
        ),
    ]
