# Generated by Django 2.2.4 on 2019-08-23 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_post_views_double_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views_double_check',
        ),
    ]
