# Generated by Django 2.2.4 on 2019-08-17 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_of',
            field=models.IntegerField(null=True),
        ),
    ]
