# Generated by Django 2.2.4 on 2019-08-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190819_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_of',
            field=models.IntegerField(null=True),
        ),
    ]
